---
title: "Project management"

---

## Motivation

Good project management is essential for making code sustainable and fit for purpose. This should not mean lots of additional meetings or box-ticking exercises! It is about making the right decisions at the right time to ensure coding work goes as smoothly as possible. You may already do some or all of what we set out here.

## 11. Set out clear aims and scope for each project

A project should have clear aims and a comprehensive specification that defines requirements before you begin coding. Without them, you will not be able to set a proportionate level of quality assurance and decide how much documentation you will need for the work. Deciding on your aims early on will keep your project focused on the end goal. The ONS [Quality Standard for Analysis](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Quality_Standards.aspx) sets out standards and expectations around project specification and assurance, including selection and assurance of methods. RAP pipelines will usually form part of a wider project that is underpinned by that standard.

You should have a clear idea of what is and is not in scope for your coding project. It should be clear to everyone involved where your responsibilities begin and end. This will depend on factors like the number of business areas involved, the complexity of the pipeline and the IT systems you will use. Make sure that other people involved in the analysis know what is in and out of scope for the project to avoid [scope creep](https://en.wikipedia.org/wiki/Scope_creep). 

## 12.	Set out your quality specifications

Ideally, all analysis code would be of the highest possible standard. Realistically, quality should be proportionate to complexity and risk. Highly complex and impactful work needs more testing, review, and documentation than a simple pipeline with lower impact. New or experimental methods and code libraries typically require more assurance than well established ones that are already widely used. The practices included here should be proportionate and sufficient for most official statistics work, but you may need to do more for mission-critical pipelines. 

Quality specifications should be determined based on what is needed to mitigate the complexity and risk of your analysis, not by the skill level in your team. If you find you have a capability gap, aim to increase your team's capability to meet appropriate quality requirements.

## 13. If appropriate, plan to open source your code

The [Government Service Manual](https://www.gov.uk/service-manual/technology/making-source-code-open-and-reusable#licensing-your-code) says that code funded by the public should be made open source unless there is a good reason not to do so. 

Plan coding projects with open source in mind, even if open sourcing the code will not be possible from the start. If you cannot open source your code in its current form, consider whether there are things you can do to make it safe to open source. There is [Analysis Function guidance](https://analysisfunction.civilservice.gov.uk/policy-store/open-sourcing-analytical-code/) and [Government Digital Service guidance](https://www.gov.uk/guidance/be-open-and-use-open-source) on how to open source code effectively and how to decide whether to open source analytical code.

## 14. Set out clear, well-defined roles and responsibilities

Everybody working on a reproducible analytical pipeline needs to understand who does what and what their roles and responsibilities are in designing, building, maintaining, running and assuring the pipeline.

Keep a record of roles and responsibilities and store it somewhere where everybody on the project can see and access it. The roles and responsibilities record should be a living document. Update it when roles and responsibilities change, people leave the project or new people join. 

People can have multiple roles and be responsible for more than one thing. Recording roles and responsibilities early on and keeping them up to date means everybody knows who to turn to when important decisions need to be made or when something goes wrong. It also means you know when an important role is not covered and can manage the risk sensibly in your succession plans.

## 15.	Make a succession plan
Code is not reproducible if only one person can understand and use it! Over reliance on particular individuals to run and maintain code or understand and explain how it works introduces serious risks to resilience and reproducibility. It can also put undue pressure on those people.

Readable and well documented code helps to mitigate this risk, especially when it is part of a bigger set of [comprehensive analysis project documentation](https://officenationalstatistics.sharepoint.com/sites/onswiki/SitePages/Documentation.aspx) but you also need to plan for how you will protect the resilience of your pipelines when people leave your team or the wider organisation.

The size of a development team depends on context, but if only one person can maintain or understand a pipeline this means you could be left unable to deliver critical outputs and with a pipeline that nobody can maintain or understand if that person leaves or becomes unavailable you.

Putting a succession plan in place helps you to mitigate risk when one or more members of your development team move on. This is about answering the question "How am I managing risks around capability to make sure I can maintain this pipeline?".

### Things to consider in a succession plan

Set out the level of resource and capability you need to manage and maintain the pipeline, both during the development phase and the longer term maintenance phase. This will give you a realistic picture of the management overhead for the pipeline. Having clear roles and responsibilities set out will help here.    

Plan to have at least two people who can understand and maintain a pipeline at all times. If this is impossible within your own team, explore how you can build resilience by sharing understanding of the pipeline across your business area, either through recruitment or by collaborating with other teams to share knowledge, and set that out in your succession plan.

Consider how you could bring in more coding resource swiftly in an emergency. Having a pooled continuous improvement resource for coding in your division or directorate is one way to increase the resource for individual pipelines and build resilience, but this will depend on how your business area implements RAP. If a central RAP team exists in your business area, think about how you can reach out to them and share resources and knowledge to improve resilience.

Ensure that risks and issues arising from limited resource or high turnover of staff are logged, either locally or via corporate risk management tools if appropriate. Escalate these risks and issues if you cannot resolve them.

Set out how you will manage the loss of key staff. You can link this to a wider business area recruitment plan if appropriate. This is about making sure that you are aware of how losing staff will affect your ability to understand and maintain pipelines and deliver outputs and that you have a process in place to manage the risk.

## 16.  Make sure your codebase has appropriate access permissions

In general, ONS code repositories should be visible to and readable by everybody in ONS so that code is easy to find and re-use.  Code repositories (both internal and open source) must be maintained carefully so that version control is used to track changes and permission to modify the code and approve changes is appropriately controlled. When people move on from a project, check whether their permissions should be updated, especially when they have worked on code repositories with restricted access.
